---
general:
  CORS:
    allowed_origins:
      - "http://sritest.io:3000"
      - "https://sritest.io"
http_client:
  user_agent: 'compatible; sritest.io; https://sritest.io'
  timeout: 8000
validator:
  protocols:
    - "http"
    - "https"
...
