app:
  image: 'gszathmari/sritest-backend:latest'
  autodestroy: always
  environment:
    - NEW_RELIC_LICENSE_KEY=secret
    - PAPERTRAILAPP_HOST=example.com
    - PAPERTRAILAPP_PORT=1234
    - 'REDIS_URL=redis://127.0.0.1:6379/0'
balancer:
  image: 'tutum/haproxy:latest'
  environment:
    - 'DEFAULT_SSL_CERT=x'
    - 'VIRTUAL_HOST=https://*:443'
  links:
    - app
  ports:
    - '443:443'
  restart: always
  roles:
    - global
